interface Compliment {
	id: number;
	text: string;
}

const Compliments: Compliment[] = [
	{ id: 0, text: 'I love your sense of humor.' },
	{ id: 1, text: 'I like the way you smile.' },
	{ id: 2, text: 'Green color suits you.' },
	{ id: 3, text: 'Your eyes are beautiful.' },
	{ id: 4, text: 'You make him feel safe.' },
	{ id: 5, text: 'You make me happy.' },
	{ id: 6, text: 'What would I do without you?' },
	{ id: 7, text: 'You are perfect.' },
	{ id: 8, text: 'You are incredibly beautiful.' },
	{ id: 9, text: 'You are my other half.' },
	{ id: 10, text: 'You are adorable.' },
	{ id: 11, text: "You're doing great." },
	{ id: 12, text: "I'm glad you make me happy." },
	{ id: 13, text: 'Facial hairstyle.' },
	{ id: 14, text: 'You have a magical smile.' },
	{ id: 15, text: 'Life becomes more colorful around you.' },
	{ id: 16, text: 'I really appreciate your efforts.' },
	{ id: 17, text: 'I like being with you.' },
	{ id: 18, text: 'I love cuddling with you.' },
	{ id: 19, text: 'You are an amazing person.' },
	{ id: 20, text: 'You are sweeter than chocolate!' },
	{ id: 21, text: 'You have great character.' },
	{ id: 22, text: 'Every day I miss you even more.' },
	{ id: 23, text: 'I love listening to you.' },
	{ id: 24, text: 'I am incredibly happy to have you.' },
	{ id: 25, text: 'You have beautiful eyes.' },
	{ id: 26, text: 'I love your smile.' },
	{ id: 27, text: 'Your hair is so soft.' },
	{ id: 28, text: 'You have a perfect body.' },
	{ id: 29, text: 'You are so sexy.' },
	{ id: 30, text: 'You have great style.' },
	{ id: 31, text: 'The tone of your voice soothes my soul.' },
	{ id: 32, text: 'Only with you I know what it means to live.' },
	{ id: 33, text: 'Your smile brightens my every day.' },
	{
		id: 34,
		text: "You made an amazing impression on me from the very first moment and it doesn't go away.",
	},
	{ id: 35, text: 'I like every inch of your body.' },
	{ id: 36, text: 'I miss you like never before.' },
	{ id: 37, text: 'You are fooling with your beauty.' },
	{ id: 38, text: 'With you I discovered what happiness is.' },
	{ id: 39, text: 'You brighten up my every day.' },
	{ id: 40, text: 'You are so smart and beautiful.' },
	{ id: 41, text: "I don't know anyone more special." },
	{ id: 42, text: 'You are a true miracle.' },
	{ id: 43, text: 'You are a delight to my eyes.' },
	{ id: 44, text: 'There is nothing softer than your skin.' },
	{ id: 45, text: 'You are a real angel.' },
	{ id: 46, text: 'There is no one like you in the world.' },
	{ id: 47, text: "You're the best!" },
];

export default Compliments;
