interface Compliment {
	id: number;
	text: string;
}

const Compliments: Compliment[] = [
	{ id: 1, text: 'I love your sense of humor.' },
	{ id: 2, text: 'I like the way you smile.' },
	{ id: 3, text: 'This color suits you.' },
	{ id: 4, text: 'Your eyes are beautiful.' },
	{ id: 5, text: 'You are an exceptional mother.' },
	{ id: 6, text: 'You make him feel safe.' },
	{ id: 7, text: 'You make me happy.' },
	{ id: 8, text: 'What would I do without you?' },
	{ id: 9, text: 'I admire you for your courage.' },
	{ id: 10, text: 'You are perfect.' },
	{ id: 11, text: 'You are incredibly beautiful.' },
	{ id: 12, text: 'You are my other half.' },
	{ id: 13, text: 'You are adorable.' },
	{ id: 14, text: "You're doing great at this." },
	{ id: 15, text: 'Nothing attracts me more than the tone of your voice.' },
	{ id: 16, text: "I'm glad you make me happy." },
	{ id: 17, text: 'Facial hairstyle.' },
	{ id: 18, text: 'You have a magical smile.' },
	{ id: 19, text: 'Maybe life becomes more colorful around you.' },
	{ id: 20, text: 'I really appreciate your efforts.' },
	{ id: 21, text: 'I like being with you.' },
	{ id: 22, text: 'I envy you such hair.' },
	{ id: 23, text: 'If I get lost, I will find myself in your eyes.' },
	{ id: 24, text: "It's a special gift that you can care for others so much." },
	{ id: 25, text: 'I love cuddling with you.' },
	{ id: 26, text: 'All the girls look pale next to you.' },
	{ id: 27, text: 'You are an amazing person.' },
	{ id: 28, text: 'You are sweeter than chocolate!' },
	{ id: 29, text: 'You know that other girls have complexes because of you.' },
	{ id: 30, text: 'You have great character.' },
	{ id: 31, text: 'Your beauty intimidates me.' },
	{ id: 32, text: 'Every day I miss you even more.' },
	{ id: 33, text: 'I love listening to you.' },
	{ id: 34, text: 'I am incredibly happy to have you.' },
	{ id: 35, text: 'You have beautiful eyes.' },
	{ id: 36, text: 'I love your smile.' },
	{ id: 37, text: 'Your hair is so soft.' },
	{ id: 38, text: 'You have a perfect body.' },
	{ id: 39, text: 'You are so sexy.' },
	{ id: 40, text: 'You have great style.' },
	{ id: 41, text: 'The tone of your voice soothes my soul.' },
	{ id: 42, text: 'You dazzle with your inner glow.' },
	{ id: 43, text: 'Only with you I know what it means to live.' },
	{ id: 44, text: 'Your smile brightens my every day.' },
	{
		id: 45,
		text: "You made an amazing impression on me from the very first moment and it doesn't go away.",
	},
	{ id: 46, text: 'I like every inch of your body.' },
	{ id: 47, text: 'I miss you like never before.' },
	{ id: 48, text: 'I bow to your patience with my character…' },
	{ id: 49, text: 'You are fooling with your beauty.' },
	{ id: 50, text: 'With you I discovered what happiness is.' },
	{ id: 51, text: 'You brighten up my every day.' },
	{ id: 52, text: "It's hard for me to focus around you." },
	{ id: 53, text: 'You are so smart and beautiful.' },
	{ id: 54, text: "I don't know anyone more special." },
	{ id: 55, text: 'You are a true miracle.' },
	{ id: 56, text: 'You are a delight to my eyes.' },
	{ id: 57, text: 'There is nothing softer than your skin.' },
	{ id: 58, text: 'You are a real angel.' },
	{ id: 59, text: 'There is no one like you in the world.' },
	{ id: 60, text: "You're the best!" },
];

export default Compliments;
